### ISSUE TITLE
Running the application with one command and npm

### ISSUE THREAD

**Issue by leandrocunha** [allangrds/PiuPiu#5]
I think we can just run npm start and fire the application.

**Comment by fllprbt** [comment]
If I understood correctly, you want to merge npm install and npm start in one command?

**Comment by leandrocunha** [comment]
No. To run the application, I don't see the necessity to type npm run build and after that type npm start.
We can use npm-run-all package to join this two commands.

**Comment by fllprbt** [comment]
Sure, let me do it. Is `npm start` a good name?
